-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;

-- PRUEBAS.dbo.TB_CAT_AREA definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_CAT_AREA;

CREATE TABLE PRUEBAS.dbo.TB_CAT_AREA (
	CAT_AREA_ID int NOT NULL,
	NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_CAT_A__955E14DEBA2C4B21 PRIMARY KEY (CAT_AREA_ID)
);


-- PRUEBAS.dbo.TB_CAT_FAM_CALIBER definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_CAT_FAM_CALIBER;

CREATE TABLE PRUEBAS.dbo.TB_CAT_FAM_CALIBER (
	CAT_FAM_CALIBER_ID int NOT NULL,
	NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_CAT_F__4305E750ED098A9B PRIMARY KEY (CAT_FAM_CALIBER_ID)
);


-- PRUEBAS.dbo.TB_CAT_LINE definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_CAT_LINE;

CREATE TABLE PRUEBAS.dbo.TB_CAT_LINE (
	CAT_LINE_ID int NOT NULL,
	CAT_AREA_ID int NOT NULL,
	NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_CAT_L__7D59C8F3B73F8C2A PRIMARY KEY (CAT_LINE_ID)
);


-- PRUEBAS.dbo.TB_CAT_MACHINE definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_CAT_MACHINE;

CREATE TABLE PRUEBAS.dbo.TB_CAT_MACHINE (
	MACHINE_ID int NOT NULL,
	NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_CAT_M__DE783B992DFEFABE PRIMARY KEY (MACHINE_ID)
);


-- PRUEBAS.dbo.TB_CAT_MADE_UP definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_CAT_MADE_UP;

CREATE TABLE PRUEBAS.dbo.TB_CAT_MADE_UP (
	CAT_MADE_UP_ID int NOT NULL,
	NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_CAT_M__C717BF52FB13633A PRIMARY KEY (CAT_MADE_UP_ID)
);


-- PRUEBAS.dbo.TB_CAT_SHUTDOWN definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_CAT_SHUTDOWN;

CREATE TABLE PRUEBAS.dbo.TB_CAT_SHUTDOWN (
	CAT_SHUTDOWN_ID int NOT NULL,
	NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_CAT_S__40D9A0D405362E92 PRIMARY KEY (CAT_SHUTDOWN_ID)
);


-- PRUEBAS.dbo.TB_MEASUREMENT_LIVE definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_MEASUREMENT_LIVE;

CREATE TABLE PRUEBAS.dbo.TB_MEASUREMENT_LIVE (
	VARIABLE_ID int NULL,
	NAME varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VALUE float NULL,
	UNIT int NULL
);


-- PRUEBAS.dbo.USUARIOS definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.USUARIOS;

CREATE TABLE PRUEBAS.dbo.USUARIOS (
	ID varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NOMBRE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONTRASENA varbinary(8000) NOT NULL,
	ROL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK__USUARIOS__3214EC27EA6101B6 PRIMARY KEY (ID)
);


-- PRUEBAS.dbo.sysdiagrams definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.sysdiagrams;

CREATE TABLE PRUEBAS.dbo.sysdiagrams (
	name sysname COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	principal_id int NOT NULL,
	diagram_id int IDENTITY(1,1) NOT NULL,
	version int NULL,
	definition varbinary(MAX) NULL,
	CONSTRAINT PK__sysdiagr__C2B05B616D550EED PRIMARY KEY (diagram_id),
	CONSTRAINT UK_principal_name UNIQUE (principal_id,name)
);
CREATE UNIQUE NONCLUSTERED INDEX UK_principal_name ON PRUEBAS.dbo.sysdiagrams (principal_id, name);


-- PRUEBAS.dbo.TB_FACTORY definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_FACTORY;

CREATE TABLE PRUEBAS.dbo.TB_FACTORY (
	FACTORY_ID int IDENTITY(1,1) NOT NULL,
	CAT_AREA_ID int NOT NULL,
	CAT_LINE_ID int NOT NULL,
	PRDT_KEPWARE_CHANEL_DEVICE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CMX_KEPWARE_CHANEL_DEVICE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BRAND varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IP varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_FACTO__BE9E49EF07CA1AD8 PRIMARY KEY (FACTORY_ID),
	CONSTRAINT FK__TB_FACTOR__CAT_A__71D1E811 FOREIGN KEY (CAT_AREA_ID) REFERENCES PRUEBAS.dbo.TB_CAT_AREA(CAT_AREA_ID),
	CONSTRAINT FK__TB_FACTOR__CAT_L__72C60C4A FOREIGN KEY (CAT_LINE_ID) REFERENCES PRUEBAS.dbo.TB_CAT_LINE(CAT_LINE_ID)
);


-- PRUEBAS.dbo.TB_VARIABLE definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_VARIABLE;

CREATE TABLE PRUEBAS.dbo.TB_VARIABLE (
	VARIABLE_ID int IDENTITY(1,1) NOT NULL,
	CAT_AREA_ID int NOT NULL,
	CAT_LINE_ID int NOT NULL,
	NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TAG varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ADDRESS varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNIT varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FREQUENCY_MINUTES varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPE] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_VARIA__0417CA69C36127B9 PRIMARY KEY (VARIABLE_ID),
	CONSTRAINT FK__TB_VARIAB__CAT_A__0B91BA14 FOREIGN KEY (CAT_AREA_ID) REFERENCES PRUEBAS.dbo.TB_CAT_AREA(CAT_AREA_ID),
	CONSTRAINT FK__TB_VARIAB__CAT_L__0C85DE4D FOREIGN KEY (CAT_LINE_ID) REFERENCES PRUEBAS.dbo.TB_CAT_LINE(CAT_LINE_ID)
);


-- PRUEBAS.dbo.TB_MEASUREMENT definition

-- Drop table

-- DROP TABLE PRUEBAS.dbo.TB_MEASUREMENT;

CREATE TABLE PRUEBAS.dbo.TB_MEASUREMENT (
	MEASUREMENT_ID int IDENTITY(1,1) NOT NULL,
	VARIABLE_ID int NOT NULL,
	NAME char(120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATE] datetime NULL,
	[HOUR] varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VALUE float NULL,
	UNIT varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TB_MEASU__EB5183F4F19DE836 PRIMARY KEY (MEASUREMENT_ID),
	CONSTRAINT FK__TB_MEASUR__VARIA__0D7A0286 FOREIGN KEY (VARIABLE_ID) REFERENCES PRUEBAS.dbo.TB_VARIABLE(VARIABLE_ID)
);

