DROP DATABASE IF EXISTS PRUEBAS;
CREATE DATABASE PRUEBAS;
USE PRUEBAS;

CREATE TABLE USUARIOS(
    ID INT(5) ZEROFILL PRIMARY KEY,
    USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(50) NOT NULL,
    ROL VARCHAR(50) NOT NULL,
    FECHACREACION   DATETIME NOT NULL
);

INSERT INTO USUARIOS (ID, USUARIO, CONTRASENA, ROL, FECHACREACION) VALUES (
    1,"JUAN PEREZ","12345678A","ADMINISTRADOR", NOW()
);

SELECT * FROM USUARIOS;
